os: linux
language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

stages:
  - test
  - name: deploy
    if: tag IS present

before_install:
  - pip install --upgrade pip
  - pip install poetry
  - pip install codecov
install:
  - poetry install --no-root -v
script:
  - make ci
  - make cover
#  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: deploy
      os: linux
      language: python
      dist: xenial
      python: "3.8"
      script: skip
      after_success: skip
      deploy:
        provider: script
        script: poetry publish -u __token__ -p $PYPI_PASSWORD -n --build
        on:
          tags: true

after_success:
  - codecov
